package org.example.eventiapro.model;

import jakarta.persistence.*;
import java.sql.Timestamp;

/**
 * Represents Registrations in the system.
 * Each registration has a user_id,an
 * event_id,registration_date,username,eventTitle,event,status
 * 
 * This class is mapped to the "registrations" table in the database using JPA
 * annotations.
 *
 * @author DELICE KEZA
 * @version 1.0
 */

@Entity
@Table(name = "registrations", uniqueConstraints = { @UniqueConstraint(columnNames = { "user_id", "event_id" }) })
/** Unique identifier for the registration. Auto-generated by the database. */
public class Registration {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    /** user_id of the user. Cannot be null. */
    @Column(name = "user_id")
    private int userId;
    /** The id of the event you want to register. Cannot be null. */
    @Column(name = "event_id")
    private int eventId;
    /** The date you registered. Cannot be null. */
    @Column(name = "registration_date", insertable = false, updatable = false, columnDefinition = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    private Timestamp registrationDate;

    // Join fields (marked as Transient for Hibernate)
    @Transient
    private String username;
    @Transient
    private String eventTitle;
    @Transient
    private Event event;
    @Column(name = "status")
    private String status = "Upcoming"; // Default status

    public Registration() {
    }

    /**
     * Constructs a new Registration with all properties.
     *
     * @param id               unique identifier
     * @param userId           user id in the Registration
     * @param eventId          event id in the Registration
     * @param registrationDate time of registering
     */

    public Registration(int id, int userId, int eventId, Timestamp registrationDate) {
        this.id = id;
        this.userId = userId;
        this.eventId = eventId;
        this.registrationDate = registrationDate;
    }

    // Getters and Setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public int getEventId() {
        return eventId;
    }

    public void setEventId(int eventId) {
        this.eventId = eventId;
    }

    public Timestamp getRegistrationDate() {
        return registrationDate;
    }

    public void setRegistrationDate(Timestamp registrationDate) {
        this.registrationDate = registrationDate;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEventTitle() {
        return eventTitle;
    }

    public void setEventTitle(String eventTitle) {
        this.eventTitle = eventTitle;
    }

    public Event getEvent() {
        return event;
    }

    public void setEvent(Event event) {
        this.event = event;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}
