package org.example.eventiapro.model;

import jakarta.persistence.*;
import java.sql.Timestamp;


/**
 * Represents a Saved Event in the system.
 * Each saved event has an id,user_id,event_id,saved_at
 * This class is mapped to the "events" table in the database using JPA annotations.
 *
 * @author DELICE KEZA
 * @version 1.0
 */
@Entity
@Table(name = "saved_events")
public class SavedEvent {
    /** Unique identifier for the event. Auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /** user id of the event visitor. Cannot be null. */
    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /** event id of the event. Cannot be null. */
    @ManyToOne
    @JoinColumn(name = "event_id", nullable = false)
    private Event event;

    /** Date if saving the event. Cannot be null. */
    @Column(name = "saved_at", insertable = false, updatable = false, columnDefinition = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    private Timestamp savedAt;

    public SavedEvent() {
    }
    /**
     * Constructs a new Saved Event with all properties.
     *

     * @param user user of the event
     * @param event name of the event
     */
    public SavedEvent(User user, Event event) {
        this.user = user;
        this.event = event;
    }

    // Getters and Setters
    /**
     * Gets the id.
     *
     * @return the id
     */
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
    /**
     * Gets the user
     *
     * @return user
     */

    public User getUser() {
        return user;
    }


    public void setUser(User user) {
        this.user = user;
    }
    /**
     * Gets the event title.
     *
     * @return event title
     */

    public Event getEvent() {
        return event;
    }

    public void setEvent(Event event) {
        this.event = event;
    }
    /**
     * Gets the savedAt date.
     *
     * @return savedAt date
     */

    public Timestamp getSavedAt() {
        return savedAt;
    }


    public void setSavedAt(Timestamp savedAt) {
        this.savedAt = savedAt;
    }
}
